### ISSUE TITLE
PowerSchool 500 errors?

### ISSUE THREAD

**Issue by HeartlandTechie** [grantholle/laravel-powerschool-auth#4]
Any ideas on how to track down 500 errors on PS when using this?  I think I have everything setup right . . . but not sure.  On the Oauth2 version is the controller named right in the documentation?     Should it have been PowerSchoolOidcLoginController?

> `class PowerSchoolOidcController extends Controller
{
    use AuthenticatesUsingPowerSchoolWithOidc;`

**Comment by grantholle** [comment]
When I've seen 500 errors it's because the redirect url doesn't match the one that's configured. I would make sure that if you're using the plain trait and no modifications to the routes in the example.

If your route doesn't match `/auth/powerschool/oidc`, then you'll have to add and modify this function in your controller:

```php
protected function getRedirectUrl()
{
    // Change this path to match whatever is in your `web.php` routes file
    return url('/auth/powerschool/oidc');
}
```

**Comment by grantholle** [comment]
And that it matches the one set in the plugin configuration under Data Provider Configuration in the plugin setup

**Comment by HeartlandTechie** [comment]
Fixed.  Thank you.
