### ISSUE TITLE
Authenticated user from PowerSchool overwrites first user

### ISSUE THREAD

**Issue by HeartlandTechie** [grantholle/laravel-powerschool-auth#5]
When I authenticate a user, the info just uses the first user in my table and puts all the info there.  If I log in a second PowerSchool user they overwrite the first users data.  Thoughts?

**Comment by grantholle** [comment]
Hmm. A couple questions:

1. Are you using OpenID 2.0 or OpenID Connect?
2. What do you have configured for the `identifying_attributes` config option?

**Comment by HeartlandTechie** [comment]
@grantholle 
OpenID Connect is what I'm using.

Here is my powerschool-auth file for the student:

` 'student' => [
        'allowed' => true,
        'model' => \App\Models\User::class,
        'attributes' => [
            'firstName' => 'first_name',
            'lastName' => 'last_name',
            'name'=>'lastfirst',
            'email' => 'email',
            'given_name' => 'first_name',
            'family_name' => 'last_name',
            'ps_dcid' => 'ps_dcid'
        ],
        'guard' => 'web',
        'identifying_attributes' => [
            'openid_claimed_id' => 'openid_identity',
        ],
        'attribute_transformers' => [
            'email' => \GrantHolle\PowerSchool\Auth\Transformers\Lowercase::class,
        ],
        'redirectTo' => '',
    ],`

**Comment by grantholle** [comment]
I think the issue is that there isn't the `openid_claimed_id` property in the OIDC payload, so when it tries to look up the student it will just grab the first record where the `openid_identity` column is null, which will always be just the first record.

If you check out the [example payloads](https://github.com/grantholle/laravel-powerschool-auth#example-data), I would probably use the `oid2` from the payload to map to your `openid_identity` column. So something like this:

```php
//
'identifying_attributes' => [ 
    'oid2' => 'openid_identity',
],
//
```

This way there will be a unique identifier for a student.

**Comment by HeartlandTechie** [comment]
Ok, I went back and tweaked a few things and now I believe it's working finally.  Thank you!

**Comment by grantholle** [comment]
Awesome, good to hear
